OesApi: Z:/Swordfish/2.Src.C/oes/sources/libraries/oes_api/oes_async_api.c File Reference
oes_async_api.c File Reference
OES 异步接口库
Functions
OesAsyncApiContextT * OesAsyncApi_CreateContext (char *pCfgFile)
创建异步API的运行时环境 (通过配置文件和默认的配置区段加载相关配置参数)
OesAsyncApiContextT * OesAsyncApi_CreateContext2 (char *pCfgFile, char *pLoggerSection, char *pAsyncApiSection, char *pCpusetSection)
创建异步API的运行时环境 (通过配置文件和指定的配置区段加载相关配置参数)
OesAsyncApiContextT * OesAsyncApi_CreateContextSimple (char *pLoggerCfgFile, char *pLoggerSection, int32 asyncQueueSize)
创建异步API的运行时环境 (仅通过函数参数指定必要的配置参数)
OesAsyncApiContextT * OesAsyncApi_CreateContextSimple2 (char *pLoggerCfgFile, char *pLoggerSection, OesAsyncApiContextParamsT *pContextParams)
创建异步API的运行时环境 (仅通过函数参数指定必要的配置参数)
void OesAsyncApi_ReleaseContext (OesAsyncApiContextT *pAsyncContext)
释放异步API的运行时环境
int OesAsyncApi_Start (OesAsyncApiContextT *pAsyncContext)
启动异步API线程
void OesAsyncApi_Stop (OesAsyncApiContextT *pAsyncContext)
终止异步API线程
int OesAsyncApi_IsRunning (OesAsyncApiContextT *pAsyncContext)
返回异步API的通信线程是否正在运行过程中
int OesAsyncApi_IsAllTerminated (OesAsyncApiContextT *pAsyncContext)
返回异步API相关的所有线程是否都已经安全退出 (或尚未运行)
int64 OesAsyncApi_GetTotalPicked (OesAsyncApiContextT *pAsyncContext)
返回异步API累计已提取和处理过的回报/应答消息数量
int64 OesAsyncApi_GetAsyncQueueTotalCount (OesAsyncApiContextT *pAsyncContext)
返回异步API累计已入队的消息数量
int64 OesAsyncApi_GetAsyncQueueRemainingCount (OesAsyncApiContextT *pAsyncContext)
返回队列中尚未被处理的剩余数据数量
int32 OesAsyncApi_GetChannelCount (OesAsyncApiContextT *pAsyncContext)
返回通道数量 (通道配置信息数量)
int32 OesAsyncApi_GetConnectedChannelCount (OesAsyncApiContextT *pAsyncContext)
返回当前已连接的通道数量
OesAsyncApiChannelT * OesAsyncApi_AddChannel (OesAsyncApiContextT *pAsyncContext, eOesApiChannelTypeT channelType, char *pChannelTag, OesApiRemoteCfgT *pRemoteCfg, OesApiSubscribeInfoT *pSubscribeCfg, F_OESAPI_ASYNC_ON_MSG_T fnOnMsg, void *pOnMsgParams, F_OESAPI_ASYNC_ON_CONNECT_T fnOnConnect, void *pOnConnectParams, F_OESAPI_ASYNC_ON_DISCONNECT_T fnOnDisconnect, void *pOnDisconnectParams)
添加通道配置信息
OesAsyncApiChannelT * OesAsyncApi_AddChannelFromFile (OesAsyncApiContextT *pAsyncContext, eOesApiChannelTypeT channelType, char *pChannelTag, char *pCfgFile, char *pCfgSection, char *pAddrKey, F_OESAPI_ASYNC_ON_MSG_T fnOnMsg, void *pOnMsgParams, F_OESAPI_ASYNC_ON_CONNECT_T fnOnConnect, void *pOnConnectParams, F_OESAPI_ASYNC_ON_DISCONNECT_T fnOnDisconnect, void *pOnDisconnectParams)
从配置文件中加载通道配置信息, 并添加到异步API线程配置中
OesAsyncApiChannelT * OesAsyncApi_GetChannel (OesAsyncApiContextT *pAsyncContext, int32 channelType, int32 channelIndex)
返回顺序号对应的连接通道信息
OesAsyncApiChannelT * OesAsyncApi_GetChannelByTag (OesAsyncApiContextT *pAsyncContext, int32 channelType, char *pChannelTag)
返回标签对应的连接通道信息
int32 OesAsyncApi_ForeachChannel (OesAsyncApiContextT *pAsyncContext, int32 channelType, int32(*fnCallback)(OesAsyncApiChannelT *pAsyncChannel, void *pParams), void *pParams)
遍历所有的连接通道信息并执行回调函数
int32 OesAsyncApi_ForeachChannel2 (OesAsyncApiContextT *pAsyncContext, int32 channelType, int32(*fnCallback)(OesAsyncApiChannelT *pAsyncChannel, void *pParam1, void *pParam2), void *pParam1, void *pParam2)
遍历所有的连接通道信息并执行回调函数
int32 OesAsyncApi_ForeachChannel3 (OesAsyncApiContextT *pAsyncContext, int32 channelType, int32(*fnCallback)(OesAsyncApiChannelT *pAsyncChannel, void *pParam1, void *pParam2, void *pParam3), void *pParam1, void *pParam2, void *pParam3)
遍历所有的连接通道信息并执行回调函数
int OesAsyncApi_IsChannelConnected (OesAsyncApiChannelT *pAsyncChannel)
返回通道是否已连接就绪
OesAsyncApiChannelCfgT * OesAsyncApi_GetChannelCfg (OesAsyncApiChannelT *pAsyncChannel)
返回通道对应的配置信息
OesApiSubscribeInfoT * OesAsyncApi_GetChannelSubscribeCfg (OesAsyncApiChannelT *pAsyncChannel)
返回通道对应的回报订阅配置信息
int OesAsyncApi_RegisterSymbioticSession (OesAsyncApiChannelT *pAsyncChannel, OesApiSessionInfoT *pObserverSession)
注册和连接通道有共生关系的会话信息 当连接通道断开后将自动触发有共生关系的会话信息断开
int32 OesAsyncApi_SendOrderReq (OesAsyncApiChannelT *pAsyncOrdChannel, OesOrdReqT *pOrdReq)
发送委托申报请求 以单向异步消息的方式发送委托申报到OES服务器, OES的实时风控检查等处理结果将通过回报数据返回
int32 OesAsyncApi_SendOrderCancelReq (OesAsyncApiChannelT *pAsyncOrdChannel, OesOrdCancelReqT *pCancelReq)
发送撤单请求 以单向异步消息的方式发送委托申报到OES服务器, OES的实时风控检查等处理结果将通过回报数据返回
int32 OesAsyncApi_SendBatchOrdersReq (OesAsyncApiChannelT *pAsyncOrdChannel, OesOrdReqT *ppOrdPtrList[], int32 ordCount)
批量发送多条委托请求 以批量的形式同时发送多笔委托申报, 而风控检查等处理结果则仍以单笔委托为单位通过回报数据返回
int32 OesAsyncApi_SendBatchOrdersReq2 (OesAsyncApiChannelT *pAsyncOrdChannel, OesOrdReqT *pOrdReqArray, int32 ordCount)
批量发送多条委托请求 以批量的形式同时发送多笔委托申报, 而风控检查等处理结果则仍以单笔委托为单位通过回报数据返回
int32 OesAsyncApi_SendFundTransferReq (OesAsyncApiChannelT *pAsyncOrdChannel, OesFundTrsfReqT *pFundTrsfReq)
发送出入金委托请求 以单向异步消息的方式发送委托申报到OES服务器, OES的实时风控检查等处理结果将通过回报数据返回
int32 OesAsyncApi_SendChangePasswordReq (OesAsyncApiChannelT *pAsyncOrdChannel, OesChangePasswordReqT *pChangePasswordReq)
异步发送密码修改请求 (修改客户端登录密码) 密码修改请求将通过委托通道发送到OES服务器, 仅发送请求不接收应答消息
int32 OesAsyncApi_SendOptSettlementConfirmReq (OesAsyncApiChannelT *pAsyncOrdChannel, OesOptSettlementConfirmReqT *pOptSettlementConfirmReq, OesOptSettlementConfirmRspT *pOptSettlementConfirmRsp)
期权账户结算单确认 结算单确认请求将通过委托通道发送到OES服务器, 并将采用同步请求/应答的方式直接返回处理结果
int OesAsyncApi_SendReportSynchronization (OesAsyncApiChannelT *pAsyncRptChannel, int8 subscribeEnvId, int32 subscribeRptTypes, int64 lastRptSeqNum)
发送回报同步消息 (仅适用于回报通道)
int OesAsyncApi_SendHeartbeat (OesAsyncApiChannelT *pAsyncChannel)
发送心跳消息
int OesAsyncApi_SendTestReq (OesAsyncApiChannelT *pAsyncChannel, char *pTestReqId, int32 testReqIdSize)
发送测试请求消息
int OesAsyncApi_LoadCpusetCfg (OesAsyncApiContextT *pAsyncContext, char *pCfgFile, char *pCfgSection, char *pCommunicationCpusetKey, char *pCallbackThreadCpusetKey, char *pIoThreadCpusetKey)
从配置文件中加载CPU亲和性配置
int OesAsyncApi_SetCommunicationCpusetCfg (OesAsyncApiContextT *pAsyncContext, char *pCommunicationCpuset)
设置通信线程的CPU亲和性配置
char * OesAsyncApi_GetCommunicationCpusetCfg (OesAsyncApiContextT *pAsyncContext)
返回通信线程的CPU亲和性配置信息
int OesAsyncApi_SetCallbackThreadCpusetCfg (OesAsyncApiContextT *pAsyncContext, char *pCallbackThreadCpuset)
设置异步回调线程的CPU亲和性配置
char * OesAsyncApi_GetCallbackThreadCpusetCfg (OesAsyncApiContextT *pAsyncContext)
返回异步回调线程的CPU亲和性配置信息
int OesAsyncApi_SetIoThreadCpusetCfg (OesAsyncApiContextT *pAsyncContext, char *pIoThreadCpuset)
设置异步I/O线程的CPU亲和性配置
char * OesAsyncApi_GetIoThreadCpusetCfg (OesAsyncApiContextT *pAsyncContext)
返回异步I/O线程的CPU亲和性配置信息
int OesAsyncApi_SetPreconnectAble (OesAsyncApiContextT *pAsyncContext, int isPreconnectAble)
设置是否在启动前预创建并校验所有的连接
int OesAsyncApi_IsPreconnectAble (OesAsyncApiContextT *pAsyncContext)
返回是否在启动前预创建并校验所有的连接
int OesAsyncApi_SetTakeoverStartThreadFlag (OesAsyncApiContextT *pAsyncContext, int32 isTakeoverStartThread)
设置是否接管启动线程
int32 OesAsyncApi_GetTakeoverStartThreadFlag (OesAsyncApiContextT *pAsyncContext)
返回是否接管启动线程
int OesAsyncApi_SetAsyncCallbackAble (OesAsyncApiContextT *pAsyncContext, int isAsyncCallbackAble)
设置是否启动独立的回调线程来执行回调处理
int OesAsyncApi_IsAsyncCallbackAble (OesAsyncApiContextT *pAsyncContext)
返回是否启动独立的回调线程来执行回调处理
int OesAsyncApi_SetAsyncCallbackBusyPollAble (OesAsyncApiContextT *pAsyncContext, int isBusyPollAble)
设置异步回调线程的忙等待模式
int OesAsyncApi_IsAsyncCallbackBusyPollAble (OesAsyncApiContextT *pAsyncContext)
返回异步回调线程的忙等待模式
int64 OesAsyncApi_GetAsyncQueueLength (OesAsyncApiContextT *pAsyncContext)
返回异步通信队列的长度 (可缓存的最大消息数量)
int64 OesAsyncApi_GetAsyncQueueDataAreaSize (OesAsyncApiContextT *pAsyncContext)
返回异步通信队列的数据空间大小
int OesAsyncApi_SetIoThreadCfg (OesAsyncApiContextT *pAsyncContext, int isEnabled, int isOutputSimplify, int32 dataOutputFormat, char *pDataOutputFilePath, char *pStatsOutputFilePath)
设置异步I/O线程配置
OesAsyncApiIoThreadCfgT * OesAsyncApi_GetIoThreadCfg (OesAsyncApiContextT *pAsyncContext)
返回异步I/O线程配置
int OesAsyncApi_LoadIoThreadCfg (OesAsyncApiContextT *pAsyncContext, char *pCfgFile, char *pCfgSection)
从配置文件中加载异步I/O线程配置
Detailed Description
OES 异步接口库
Version
0.15.10 2019/11/17
Since
2019/11/17
Function Documentation
OesAsyncApi_AddChannel()
OesAsyncApiChannelT* OesAsyncApi_AddChannel (OesAsyncApiContextT * pAsyncContext, eOesApiChannelTypeT channelType, char * pChannelTag, OesApiRemoteCfgT * pRemoteCfg, OesApiSubscribeInfoT * pSubscribeCfg, F_OESAPI_ASYNC_ON_MSG_T fnOnMsg, void * pOnMsgParams, F_OESAPI_ASYNC_ON_CONNECT_T fnOnConnect, void * pOnConnectParams, F_OESAPI_ASYNC_ON_DISCONNECT_T fnOnDisconnect, void * pOnDisconnectParams)
添加通道配置信息
Note
提示:
可以将委托通道和回报通道依次添加到同一个异步线程中
异步API尚不支持查询接口, 不能将查询通道添加到异步API中
Parameters
[out] pAsyncContext 异步API的运行时环境指针
channelType 待添加的通道类型, 仅支持如下两种类型:
1: 委托通道 (
See also
OESAPI_CHANNEL_TYPE_ORDER)
2: 回报通道 (
OESAPI_CHANNEL_TYPE_REPORT)
Parameters
pChannelTag 通道配置信息的自定义标签 (可以为空)
pRemoteCfg 待添加的通道配置信息 (不可为空)
pSubscribeCfg 默认的回报订阅参数 (可以为空)
fnOnMsg 进行消息处理的回调函数 (不可为空)
pOnMsgParams fnOnMsg回调函数的参数
fnOnConnect 连接或重新连接完成后的回调函数 (可以为空)
若函数指针为空, 则会使用默认的回报订阅参数进行订阅
pOnConnectParams fnOnConnect回调函数的参数
fnOnDisconnect 连接断开后的回调函数 (可以为空)
pOnDisconnectParams fnOnDisconnect回调函数的参数
Returns
非空, 异步API的连接通道信息; 空, 失败
OesAsyncApi_AddChannelFromFile()
OesAsyncApiChannelT* OesAsyncApi_AddChannelFromFile (OesAsyncApiContextT * pAsyncContext, eOesApiChannelTypeT channelType, char * pChannelTag, char * pCfgFile, char * pCfgSection, char * pAddrKey, F_OESAPI_ASYNC_ON_MSG_T fnOnMsg, void * pOnMsgParams, F_OESAPI_ASYNC_ON_CONNECT_T fnOnConnect, void * pOnConnectParams, F_OESAPI_ASYNC_ON_DISCONNECT_T fnOnDisconnect, void * pOnDisconnectParams)
从配置文件中加载通道配置信息, 并添加到异步API线程配置中
Note
提示:
可以将委托通道和回报通道依次添加到同一个异步线程中
异步API尚不支持查询接口, 不能将查询通道添加到异步API中
Parameters
[out] pAsyncContext 异步API的运行时环境指针
channelType 待添加的通道类型, 仅支持如下两种类型:
1: 委托通道 (
See also
OESAPI_CHANNEL_TYPE_ORDER)
2: 回报通道 (
OESAPI_CHANNEL_TYPE_REPORT)
Parameters
pChannelTag 通道配置信息的自定义标签 (可以为空)
pCfgFile 配置文件路径 (不可为空)
pCfgSection 配置区段名称 (不可为空)
pAddrKey 服务器地址的配置项关键字 (不可为空)
fnOnMsg 进行消息处理的回调函数 (不可为空)
pOnMsgParams fnOnMsg回调函数的参数
fnOnConnect 连接或重新连接完成后的回调函数 (可以为空)
若函数指针为空, 则会使用默认的回报订阅参数进行订阅
pOnConnectParams fnOnConnect回调函数的参数
fnOnDisconnect 连接断开后的回调函数 (可以为空)
pOnDisconnectParams fnOnDisconnect回调函数的参数
Returns
非空, 异步API的连接通道信息; 空, 失败
OesAsyncApi_CreateContext()
OesAsyncApiContextT* OesAsyncApi_CreateContext (char * pCfgFile)
创建异步API的运行时环境 (通过配置文件和默认的配置区段加载相关配置参数)
与 OesAsyncApi_CreateContextSimple 接口的区别为, 会通过配置文件加载如下配置:
日志配置
异步API相关的扩展配置: 异步队列的大小、是否启动独立的回调线程来执行回调处理、是否使用 忙等待模式等
异步I/O线程配置 (
See also
OesAsyncApi_LoadIoThreadCfg)
CPU亲和性配置 (
See also
OesAsyncApi_LoadCpusetCfg)
Parameters
pCfgFile 配置文件路径 (可为空, 为空则不加载配置文件)
Returns
非空, 异步API的运行时环境指针; NULL, 失败
OesAsyncApi_CreateContext2()
OesAsyncApiContextT* OesAsyncApi_CreateContext2 (char * pCfgFile, char * pLoggerSection, char * pAsyncApiSection, char * pCpusetSection)
创建异步API的运行时环境 (通过配置文件和指定的配置区段加载相关配置参数)
与 OesAsyncApi_CreateContextSimple 接口的区别为, 会通过配置文件加载如下配置:
日志配置
异步API相关的扩展配置: 异步队列的大小、是否启动独立的回调线程来执行回调处理、是否使用 忙等待模式等
异步I/O线程配置 (
See also
OesAsyncApi_LoadIoThreadCfg)
CPU亲和性配置 (
See also
OesAsyncApi_LoadCpusetCfg)
Parameters
pCfgFile 配置文件路径 (可为空, 为空则不加载配置文件)
pLoggerSection 日志记录器的配置区段名称 (e.g. "log")
为空则忽略, 不初始化日志记录器
pAsyncApiSection 异步API参数的配置区段名称 (e.g. "oes_client.async_api")
为空则忽略, 不加载异步API相关的配置
pCpusetSection CPU亲和性配置的配置区段名称 (e.g. "cpuset")
为空则忽略, 不加载CPU亲和性配置
Returns
非空, 异步API的运行时环境指针; NULL, 失败
Referenced by OesAsyncApi_CreateContext().
OesAsyncApi_CreateContextSimple()
OesAsyncApiContextT* OesAsyncApi_CreateContextSimple (char * pLoggerCfgFile, char * pLoggerSection, int32 asyncQueueSize)
创建异步API的运行时环境 (仅通过函数参数指定必要的配置参数)
Parameters
pLoggerCfgFile 日志配置文件路径
为空则忽略, 不初始化日志记录器
pLoggerSection 日志记录器的配置区段名称 (e.g. "log")
为空则使用默认值
asyncQueueSize 用于缓存回报数据的消息队列大小 (最大可缓存的消息数量)
等于0, 不创建缓存队列 (无需异步处理或落地回报数据)
小于0, 使用默认值 100000
Returns
非空, 异步API的运行时环境指针; NULL, 失败
OesAsyncApi_CreateContextSimple2()
OesAsyncApiContextT* OesAsyncApi_CreateContextSimple2 (char * pLoggerCfgFile, char * pLoggerSection, OesAsyncApiContextParamsT * pContextParams)
创建异步API的运行时环境 (仅通过函数参数指定必要的配置参数)
Parameters
pLoggerCfgFile 日志配置文件路径
为空则忽略, 不初始化日志记录器
pLoggerSection 日志记录器的配置区段名称 (e.g. "log")
为空则使用默认值
pContextParams 上下文环境的创建参数
为空则使用默认值
Returns
非空, 异步API的运行时环境指针; NULL, 失败
OesAsyncApi_ForeachChannel()
int32 OesAsyncApi_ForeachChannel (OesAsyncApiContextT * pAsyncContext, int32 channelType, int32(*)(OesAsyncApiChannelT *pAsyncChannel, void *pParams) fnCallback, void * pParams)
遍历所有的连接通道信息并执行回调函数
Parameters
pAsyncContext 异步API的运行时环境指针
channelType 待遍历的通道类型
0: 所有类型
1: 委托通道 (
See also
OESAPI_CHANNEL_TYPE_ORDER)
2: 回报通道 (
OESAPI_CHANNEL_TYPE_REPORT)
Parameters
fnCallback 待执行的回调函数 (可以为空)
若返回值小于0, 则将中止遍历并返回该值
pParams 回调函数的参数 (可以为空)
Returns
大于等于0, 成功遍历到的通道数量; 小于0, 参数错误或者回调函数的返回值小于0
OesAsyncApi_ForeachChannel2()
int32 OesAsyncApi_ForeachChannel2 (OesAsyncApiContextT * pAsyncContext, int32 channelType, int32(*)(OesAsyncApiChannelT *pAsyncChannel, void *pParam1, void *pParam2) fnCallback, void * pParam1, void * pParam2)
遍历所有的连接通道信息并执行回调函数
Parameters
pAsyncContext 异步API的运行时环境指针
channelType 待遍历的通道类型
0: 所有类型
1: 委托通道 (
See also
OESAPI_CHANNEL_TYPE_ORDER)
2: 回报通道 (
OESAPI_CHANNEL_TYPE_REPORT)
Parameters
fnCallback 待执行的回调函数 (可以为空)
若返回值小于0, 则将中止遍历并返回该值
pParam1 回调函数的参数1 (可以为空)
pParam2 回调函数的参数2 (可以为空)
Returns
大于等于0, 成功遍历到的通道数量; 小于0, 参数错误或者回调函数的返回值小于0
OesAsyncApi_ForeachChannel3()
int32 OesAsyncApi_ForeachChannel3 (OesAsyncApiContextT * pAsyncContext, int32 channelType, int32(*)(OesAsyncApiChannelT *pAsyncChannel, void *pParam1, void *pParam2, void *pParam3) fnCallback, void * pParam1, void * pParam2, void * pParam3)
遍历所有的连接通道信息并执行回调函数
Parameters
pAsyncContext 异步API的运行时环境指针
channelType 待遍历的通道类型
0: 所有类型
1: 委托通道 (
See also
OESAPI_CHANNEL_TYPE_ORDER)
2: 回报通道 (
OESAPI_CHANNEL_TYPE_REPORT)
Parameters
fnCallback 待执行的回调函数 (可以为空)
若返回值小于0, 则将中止遍历并返回该值
pParam1 回调函数的参数1 (可以为空)
pParam2 回调函数的参数2 (可以为空)
pParam3 回调函数的参数3 (可以为空)
Returns
大于等于0, 成功遍历到的通道数量; 小于0, 参数错误或者回调函数的返回值小于0
OesAsyncApi_GetAsyncQueueDataAreaSize()
int64 OesAsyncApi_GetAsyncQueueDataAreaSize (OesAsyncApiContextT * pAsyncContext)
返回异步通信队列的数据空间大小
Parameters
pAsyncContext 异步API的运行时环境指针
Returns
异步通信队列的数据空间大小 (字节数)
OesAsyncApi_GetAsyncQueueLength()
int64 OesAsyncApi_GetAsyncQueueLength (OesAsyncApiContextT * pAsyncContext)
返回异步通信队列的长度 (可缓存的最大消息数量)
Parameters
pAsyncContext 异步API的运行时环境指针
Returns
异步通信队列的长度 (可缓存的最大消息数量)
OesAsyncApi_GetAsyncQueueRemainingCount()
int64 OesAsyncApi_GetAsyncQueueRemainingCount (OesAsyncApiContextT * pAsyncContext)
返回队列中尚未被处理的剩余数据数量
Parameters
pAsyncContext 异步API的运行时环境指针
Returns
队列中尚未被处理的剩余数据数量
Note
仅适用于已启用回调线程 (isAsyncCallbackAble=yes) 的运行模式
OesAsyncApi_GetAsyncQueueTotalCount()
int64 OesAsyncApi_GetAsyncQueueTotalCount (OesAsyncApiContextT * pAsyncContext)
返回异步API累计已入队的消息数量
Parameters
pAsyncContext 异步API的运行时环境指针
Returns
累计已入队的消息数量
OesAsyncApi_GetCallbackThreadCpusetCfg()
char* OesAsyncApi_GetCallbackThreadCpusetCfg (OesAsyncApiContextT * pAsyncContext)
返回异步回调线程的CPU亲和性配置信息
Parameters
pAsyncContext 异步API的运行时环境指针
Returns
CPU亲和性配置信息
OesAsyncApi_GetChannel()
OesAsyncApiChannelT* OesAsyncApi_GetChannel (OesAsyncApiContextT * pAsyncContext, int32 channelType, int32 channelIndex)
返回顺序号对应的连接通道信息
Parameters
pAsyncContext 异步API的运行时环境指针
channelType 通道类型
0: 任意类型
1: 委托通道 (
See also
OESAPI_CHANNEL_TYPE_ORDER)
2: 回报通道 (
OESAPI_CHANNEL_TYPE_REPORT)
Parameters
channelIndex 通道顺序号
大于0: 返回与指定顺序号相对应的, 并且与指定通道类型相 匹配的通道信息 (顺序号与通道配置的添加顺序一致)
小于0: 返回第一个与指定通道类型相匹配的通道信息
INT_MAX: 返回最后一个与指定通道类型相匹配的通道信息
Returns
异步API的连接通道信息
OesAsyncApi_GetChannelByTag()
OesAsyncApiChannelT* OesAsyncApi_GetChannelByTag (OesAsyncApiContextT * pAsyncContext, int32 channelType, char * pChannelTag)
返回标签对应的连接通道信息
Note
注意事项:
API不强制要求标签必须唯一, 如果标签不唯一, 则将返回第一个匹配到的通道信息
标签名称不区分大小写
Parameters
pAsyncContext 异步API的运行时环境指针
channelType 通道类型
0: 任意类型
1: 委托通道 (
See also
OESAPI_CHANNEL_TYPE_ORDER)
2: 回报通道 (
OESAPI_CHANNEL_TYPE_REPORT)
Parameters
pChannelTag 通道配置信息的自定义标签
Returns
异步API的连接通道信息
OesAsyncApi_GetChannelCfg()
OesAsyncApiChannelCfgT* OesAsyncApi_GetChannelCfg (OesAsyncApiChannelT * pAsyncChannel)
返回通道对应的配置信息
Parameters
pAsyncChannel 异步API的连接通道信息
Returns
通道配置信息
OesAsyncApi_GetChannelCount()
int32 OesAsyncApi_GetChannelCount (OesAsyncApiContextT * pAsyncContext)
返回通道数量 (通道配置信息数量)
Parameters
pAsyncContext 异步API的运行时环境指针
Returns
通道数量 (通道配置信息数量)
OesAsyncApi_GetChannelSubscribeCfg()
OesApiSubscribeInfoT* OesAsyncApi_GetChannelSubscribeCfg (OesAsyncApiChannelT * pAsyncChannel)
返回通道对应的回报订阅配置信息
Parameters
pAsyncChannel 异步API的连接通道信息
Returns
回报订阅配置信息
Referenced by OesAsyncApi_SendReportSynchronization().
OesAsyncApi_GetCommunicationCpusetCfg()
char* OesAsyncApi_GetCommunicationCpusetCfg (OesAsyncApiContextT * pAsyncContext)
返回通信线程的CPU亲和性配置信息
返回通信线程(回报接收线程)的CPU亲和性配置信息
Parameters
pAsyncContext 异步API的运行时环境指针
Returns
CPU亲和性配置信息
OesAsyncApi_GetConnectedChannelCount()
int32 OesAsyncApi_GetConnectedChannelCount (OesAsyncApiContextT * pAsyncContext)
返回当前已连接的通道数量
Parameters
pAsyncContext 异步API的运行时环境指针
Returns
已连接的通道数量
OesAsyncApi_GetIoThreadCfg()
OesAsyncApiIoThreadCfgT* OesAsyncApi_GetIoThreadCfg (OesAsyncApiContextT * pAsyncContext)
返回异步I/O线程配置
Parameters
pAsyncContext 异步API的运行时环境指针
Returns
异步I/O线程配置信息
Referenced by OesAsyncApi_SetIoThreadCfg().
OesAsyncApi_GetIoThreadCpusetCfg()
char* OesAsyncApi_GetIoThreadCpusetCfg (OesAsyncApiContextT * pAsyncContext)
返回异步I/O线程的CPU亲和性配置信息
Parameters
pAsyncContext 异步API的运行时环境指针
Returns
CPU亲和性配置信息
OesAsyncApi_GetTakeoverStartThreadFlag()
int32 OesAsyncApi_GetTakeoverStartThreadFlag (OesAsyncApiContextT * pAsyncContext)
返回是否接管启动线程
Parameters
pAsyncContext 异步API的运行时环境指针
Returns
是否接管启动线程
OesAsyncApi_GetTotalPicked()
int64 OesAsyncApi_GetTotalPicked (OesAsyncApiContextT * pAsyncContext)
返回异步API累计已提取和处理过的回报/应答消息数量
Parameters
pAsyncContext 异步API的运行时环境指针
Returns
累计已提取和处理过的消息数量 (包括已处理但处理失败的消息)
OesAsyncApi_IsAllTerminated()
int OesAsyncApi_IsAllTerminated (OesAsyncApiContextT * pAsyncContext)
返回异步API相关的所有线程是否都已经安全退出 (或尚未运行)
Parameters
pAsyncContext 异步API的运行时环境指针
Returns
TRUE 所有线程均已退出; FALSE 尚未全部退出
OesAsyncApi_IsAsyncCallbackAble()
int OesAsyncApi_IsAsyncCallbackAble (OesAsyncApiContextT * pAsyncContext)
返回是否启动独立的回调线程来执行回调处理
Parameters
pAsyncContext 异步API的运行时环境指针
Returns
是否启动独立的回调线程来执行回调处理
OesAsyncApi_IsAsyncCallbackBusyPollAble()
int OesAsyncApi_IsAsyncCallbackBusyPollAble (OesAsyncApiContextT * pAsyncContext)
返回异步回调线程的忙等待模式
Parameters
pAsyncContext 异步API的运行时环境指针
Returns
是否使用忙等待模式
OesAsyncApi_IsChannelConnected()
int OesAsyncApi_IsChannelConnected (OesAsyncApiChannelT * pAsyncChannel)
返回通道是否已连接就绪
Parameters
pAsyncChannel 异步API的连接通道信息
Returns
TRUE 已连接就绪; FALSE 尚未连接就绪
OesAsyncApi_IsPreconnectAble()
int OesAsyncApi_IsPreconnectAble (OesAsyncApiContextT * pAsyncContext)
返回是否在启动前预创建并校验所有的连接
Parameters
pAsyncContext 异步API的运行时环境指针
Returns
是否在启动前预创建并校验所有的连接
OesAsyncApi_IsRunning()
int OesAsyncApi_IsRunning (OesAsyncApiContextT * pAsyncContext)
返回异步API的通信线程是否正在运行过程中
Parameters
pAsyncContext 异步API的运行时环境指针
Returns
TRUE 正在运行过程中; FALSE 已终止或尚未运行
OesAsyncApi_LoadCpusetCfg()
int OesAsyncApi_LoadCpusetCfg (OesAsyncApiContextT * pAsyncContext, char * pCfgFile, char * pCfgSection, char * pCommunicationCpusetKey, char * pCallbackThreadCpusetKey, char * pIoThreadCpusetKey)
从配置文件中加载CPU亲和性配置
Parameters
[out] pAsyncContext 异步API的运行时环境指针
pCfgFile 配置文件路径
pCfgSection 配置区段名称
pCommunicationCpusetKey 通信线程(回报接收线程)的CPU亲和性配置项关键字
pCallbackThreadCpusetKey 异步回调线程的CPU亲和性配置项关键字
pIoThreadCpusetKey 异步I/O线程的CPU亲和性配置项关键字
Returns
TRUE 成功; FALSE 失败
OesAsyncApi_LoadIoThreadCfg()
int OesAsyncApi_LoadIoThreadCfg (OesAsyncApiContextT * pAsyncContext, char * pCfgFile, char * pCfgSection)
从配置文件中加载异步I/O线程配置
Parameters
[out] pAsyncContext 异步API的运行时环境指针
pCfgFile 配置文件路径
pCfgSection 配置区段名称
Returns
TRUE 成功; FALSE 失败
OesAsyncApi_RegisterSymbioticSession()
int OesAsyncApi_RegisterSymbioticSession (OesAsyncApiChannelT * pAsyncChannel, OesApiSessionInfoT * pObserverSession)
注册和连接通道有共生关系的会话信息 当连接通道断开后将自动触发有共生关系的会话信息断开
Parameters
pAsyncChannel 通信端点的连接通道信息
pObserverSession 有共生关系的会话信息
Returns
TRUE 成功; FALSE 失败
OesAsyncApi_ReleaseContext()
void OesAsyncApi_ReleaseContext (OesAsyncApiContextT * pAsyncContext)
释放异步API的运行时环境
Parameters
pAsyncContext 异步API的运行时环境指针
OesAsyncApi_SendBatchOrdersReq()
int32 OesAsyncApi_SendBatchOrdersReq (OesAsyncApiChannelT * pAsyncOrdChannel, OesOrdReqT * ppOrdPtrList[], int32 ordCount)
批量发送多条委托请求 以批量的形式同时发送多笔委托申报, 而风控检查等处理结果则仍以单笔委托为单位通过回报数据返回
批量委托的委托请求填充规则与单条委托完全相同, 回报处理规则也与单条委托完全相同:
每笔委托请求的 "客户委托流水号(clSeqNo)" 同样必须填充, 并需要维持在同一客户端下的唯一性
服务器端的处理结果则仍将以单笔委托为单位通过回报数据返回
Parameters
pAsyncOrdChannel 异步API的委托连接通道
ppOrdPtrList 待发送的委托请求列表 (指针数组)
ordCount 待发送的委托请求数量
Return values
0 成功
<0 失败 (负的错误号)
Exceptions
EINVAL 传入参数非法
EPIPE 连接已破裂
Others 由send()系统调用返回的错误
OesAsyncApi_SendBatchOrdersReq2()
int32 OesAsyncApi_SendBatchOrdersReq2 (OesAsyncApiChannelT * pAsyncOrdChannel, OesOrdReqT * pOrdReqArray, int32 ordCount)
批量发送多条委托请求 以批量的形式同时发送多笔委托申报, 而风控检查等处理结果则仍以单笔委托为单位通过回报数据返回
批量委托的委托请求填充规则与单条委托完全相同, 回报处理规则也与单条委托完全相同:
每笔委托请求的 "客户委托流水号(clSeqNo)" 同样必须填充, 并需要维持在同一客户端下的唯一性
服务器端的处理结果则仍将以单笔委托为单位通过回报数据返回
Parameters
pAsyncOrdChannel 异步API的委托连接通道
pOrdReqArray 待发送的委托请求数组 (连续的存储空间)
ordCount 待发送的委托请求数量
Return values
0 成功
<0 失败 (负的错误号)
Exceptions
EINVAL 传入参数非法
EPIPE 连接已破裂
Others 由send()系统调用返回的错误
OesAsyncApi_SendChangePasswordReq()
int32 OesAsyncApi_SendChangePasswordReq (OesAsyncApiChannelT * pAsyncOrdChannel, OesChangePasswordReqT * pChangePasswordReq)
异步发送密码修改请求 (修改客户端登录密码) 密码修改请求将通过委托通道发送到OES服务器, 仅发送请求不接收应答消息
Parameters
pAsyncOrdChannel 异步API的委托连接通道
[in] pChangePasswordReq 待发送的密码修改请求
Return values
0 成功
<0 API调用失败 (负的错误号)
>0 服务端业务处理失败 (OES错误号)
Exceptions
EINVAL 传入参数非法
EPIPE 连接已破裂
Others 由send()系统调用返回的错误
OesAsyncApi_SendFundTransferReq()
int32 OesAsyncApi_SendFundTransferReq (OesAsyncApiChannelT * pAsyncOrdChannel, OesFundTrsfReqT * pFundTrsfReq)
发送出入金委托请求 以单向异步消息的方式发送委托申报到OES服务器, OES的实时风控检查等处理结果将通过回报数据返回
Parameters
pAsyncOrdChannel 异步API的委托连接通道
pFundTrsfReq 待发送的出入金委托请求
Return values
0 成功
<0 失败 (负的错误号)
Exceptions
EINVAL 传入参数非法
EPIPE 连接已破裂
Others 由send()系统调用返回的错误
OesAsyncApi_SendHeartbeat()
int OesAsyncApi_SendHeartbeat (OesAsyncApiChannelT * pAsyncChannel)
发送心跳消息
Parameters
pAsyncChannel 异步API的连接通道信息
Returns
TRUE 成功; FALSE 失败
OesAsyncApi_SendOptSettlementConfirmReq()
int32 OesAsyncApi_SendOptSettlementConfirmReq (OesAsyncApiChannelT * pAsyncOrdChannel, OesOptSettlementConfirmReqT * pOptSettlementConfirmReq, OesOptSettlementConfirmRspT * pOptSettlementConfirmRsp)
期权账户结算单确认 结算单确认请求将通过委托通道发送到OES服务器, 并将采用同步请求/应答的方式直接返回处理结果
结算单确认后, 方可进行委托申报和出入金请求
Parameters
pAsyncOrdChannel 异步API的委托连接通道
[in] pOptSettlementConfirmReq 待发送的结算单确认请求
客户端仅关联一个客户时, 可传空指针或不指定客户代码
[out] pOptSettlementConfirmRsp 用于输出结算单确认请求应答的缓存区
Return values
0 成功
<0 API调用失败 (负的错误号)
>0 服务端业务处理失败 (OES错误号)
Exceptions
EINVAL 传入参数非法
EPIPE 连接已破裂
Others 由send()系统调用返回的错误
OesAsyncApi_SendOrderCancelReq()
int32 OesAsyncApi_SendOrderCancelReq (OesAsyncApiChannelT * pAsyncOrdChannel, OesOrdCancelReqT * pCancelReq)
发送撤单请求 以单向异步消息的方式发送委托申报到OES服务器, OES的实时风控检查等处理结果将通过回报数据返回
Parameters
pAsyncOrdChannel 异步API的委托连接通道
pCancelReq 待发送的撤单请求
Return values
0 成功
<0 失败 (负的错误号)
Exceptions
EINVAL 传入参数非法
EPIPE 连接已破裂
Others 由send()系统调用返回的错误
OesAsyncApi_SendOrderReq()
int32 OesAsyncApi_SendOrderReq (OesAsyncApiChannelT * pAsyncOrdChannel, OesOrdReqT * pOrdReq)
发送委托申报请求 以单向异步消息的方式发送委托申报到OES服务器, OES的实时风控检查等处理结果将通过回报数据返回
Parameters
pAsyncOrdChannel 异步API的委托连接通道
pOrdReq 待发送的委托申报请求
Return values
0 成功
<0 失败 (负的错误号)
Exceptions
EINVAL 传入参数非法
EPIPE 连接已破裂
Others 由send()系统调用返回的错误
OesAsyncApi_SendReportSynchronization()
int OesAsyncApi_SendReportSynchronization (OesAsyncApiChannelT * pAsyncRptChannel, int8 subscribeEnvId, int32 subscribeRptTypes, int64 lastRptSeqNum)
发送回报同步消息 (仅适用于回报通道)
Parameters
pAsyncRptChannel 异步API的回报连接通道
subscribeEnvId 待订阅的客户端环境号
大于0, 区分环境号, 仅订阅环境号对应的回报数据
等于0, 不区分环境号, 订阅该客户下的所有回报数据
小于0, 复用添加通道时指定的默认配置
Note
此处与同步API不同. 小于0时, 同步API为不区 分环境号
Parameters
subscribeRptTypes 待订阅的回报消息种类 (e.g. OES_SUB_RPT_TYPE_ORDER_INSERT | OES_SUB_RPT_TYPE_ORDER_REPORT | OES_SUB_RPT_TYPE_TRADE_REPORT)
See also
eOesSubscribeReportTypeT
小于0, 复用添加通道时指定的默认配置
Note
此处与同步API不同. 小于0时, 同步API为订阅 所有类型的消息
Parameters
lastRptSeqNum 客户端最后接收到的回报数据的回报编号
等于0, 从头开始推送回报数据
大于0, 从指定的回报编号开始推送回报数据
小于0, 从上次接收到的断点位置开始
Note
此处与同步API不同. 小于0时, 同步API为从最 新的数据开始推送回报数据
如果明确需要只从最新的数据开始推送回报数据, 可以指 定一个特别大的数 (例如 INT_MAX)
Returns
TRUE 成功; FALSE 失败
OesAsyncApi_SendTestReq()
int OesAsyncApi_SendTestReq (OesAsyncApiChannelT * pAsyncChannel, char * pTestReqId, int32 testReqIdSize)
发送测试请求消息
Parameters
pAsyncChannel 异步API的连接通道信息
pTestReqId 测试请求标识符 (C32, 可以为空)
testReqIdSize 测试请求标识符的长度
Returns
TRUE 成功; FALSE 失败
OesAsyncApi_SetAsyncCallbackAble()
int OesAsyncApi_SetAsyncCallbackAble (OesAsyncApiContextT * pAsyncContext, int isAsyncCallbackAble)
设置是否启动独立的回调线程来执行回调处理
Parameters
pAsyncContext 异步API的运行时环境指针
isAsyncCallbackAble 是否启动独立的回调线程来执行回调处理
TRUE: 创建单独的回调线程
FALSE: 不启动单独的回调线程, 直接在通信线程下执行回调处理 (默认行为)
Returns
TRUE 成功; FALSE 失败
OesAsyncApi_SetAsyncCallbackBusyPollAble()
int OesAsyncApi_SetAsyncCallbackBusyPollAble (OesAsyncApiContextT * pAsyncContext, int isBusyPollAble)
设置异步回调线程的忙等待模式
Parameters
[out] pAsyncContext 异步API的运行时环境指针
isBusyPollAble 是否使用忙等待模式 TRUE: 使用忙等待模式, 延迟更低, 但CPU会被100占用 FALSE: 不使用忙等待模式, 延迟和CPU使用率相对均衡
Returns
TRUE 成功; FALSE 失败
OesAsyncApi_SetCallbackThreadCpusetCfg()
int OesAsyncApi_SetCallbackThreadCpusetCfg (OesAsyncApiContextT * pAsyncContext, char * pCallbackThreadCpuset)
设置异步回调线程的CPU亲和性配置
Parameters
[out] pAsyncContext 异步API的运行时环境指针
pCallbackThreadCpuset 异步回调线程绑定的CPU列表 (以逗号或空格分割的CPU编号列表, CPU编号从1开始)
e.g. "1" 绑定到 0 号核
e.g. "1,3,5" 绑定到 0,2,4 号核
NULL 或者 "", 不绑定CPU
Returns
TRUE 成功; FALSE 失败
OesAsyncApi_SetCommunicationCpusetCfg()
int OesAsyncApi_SetCommunicationCpusetCfg (OesAsyncApiContextT * pAsyncContext, char * pCommunicationCpuset)
设置通信线程的CPU亲和性配置
Parameters
[out] pAsyncContext 异步API的运行时环境指针
pCommunicationCpuset 通信线程绑定的CPU列表 (以逗号或空格分割的CPU编号列表, CPU编号从1开始)
e.g. "1" 绑定到 0 号核
e.g. "1,3,5" 绑定到 0,2,4 号核
NULL 或者 "", 不绑定CPU
Returns
TRUE 成功; FALSE 失败
OesAsyncApi_SetIoThreadCfg()
int OesAsyncApi_SetIoThreadCfg (OesAsyncApiContextT * pAsyncContext, int isEnabled, int isOutputSimplify, int32 dataOutputFormat, char * pDataOutputFilePath, char * pStatsOutputFilePath)
设置异步I/O线程配置
Parameters
[out] pAsyncContext 异步API的运行时环境指针
isEnabled 使能标志
isOutputSimplify 是否采用精简模式输出数据
dataOutputFormat 数据输出格式
pDataOutputFilePath 数据文件输出路径 (为空:不输出数据; STDOUT/STDERR:标准输出)
pStatsOutputFilePath 统计信息文件输出路径 (为空:不输出数据; STDOUT/STDERR:标准输出)
Returns
TRUE 成功; FALSE 失败
OesAsyncApi_SetIoThreadCpusetCfg()
int OesAsyncApi_SetIoThreadCpusetCfg (OesAsyncApiContextT * pAsyncContext, char * pIoThreadCpuset)
设置异步I/O线程的CPU亲和性配置
Parameters
[out] pAsyncContext 异步API的运行时环境指针
pIoThreadCpuset 异步I/O线程绑定的CPU列表 (以逗号或空格分割的CPU编号列表, CPU编号从1开始)
e.g. "1" 绑定到 0 号核
e.g. "1,3,5" 绑定到 0,2,4 号核
NULL 或者 "", 不绑定CPU
Returns
TRUE 成功; FALSE 失败
OesAsyncApi_SetPreconnectAble()
int OesAsyncApi_SetPreconnectAble (OesAsyncApiContextT * pAsyncContext, int isPreconnectAble)
设置是否在启动前预创建并校验所有的连接
Parameters
pAsyncContext 异步API的运行时环境指针
isPreconnectAble 是否在启动前预创建并校验所有的连接 TRUE: 启动前预创建并校验所有的连接, 如果连接失败则中止启动 FALSE: 启动前不预先创建和校验连接 (默认行为)
Returns
TRUE 成功; FALSE 失败
OesAsyncApi_SetTakeoverStartThreadFlag()
int OesAsyncApi_SetTakeoverStartThreadFlag (OesAsyncApiContextT * pAsyncContext, int32 isTakeoverStartThread)
设置是否接管启动线程
Parameters
pAsyncContext 异步API的运行时环境指针
isTakeoverStartThread 设置是否接管启动线程
0: 启动时将创建独立的线程执行通信处理 (默认行为)
1: 无需创建独立的通信线程, 启动时将接管当前线程并直接 在当前线程下执行通信处理
CHAR_MAX: 不创建通信线程, 也不执行除OnConnect回调以 外的任何消息接收等异步处理, 完全由当前线程控制后续的执 行 (仅适用于测试场景, 正常情况下不会使用)
Returns
TRUE 成功; FALSE 失败
OesAsyncApi_Start()
int OesAsyncApi_Start (OesAsyncApiContextT * pAsyncContext)
启动异步API线程
Parameters
pAsyncContext 异步API的运行时环境指针
Returns
TRUE 成功; FALSE 失败
OesAsyncApi_Stop()
void OesAsyncApi_Stop (OesAsyncApiContextT * pAsyncContext)
终止异步API线程
Parameters
pAsyncContext 异步API的运行时环境指针